# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: node:14
#     steps:
#       - checkout
#       - run:
#           name: Run tests
#           command: |
#             npm install
#             npm test
#             node index
#   deploy:
#     docker:
#       - image: node:14
#     steps:
#       - checkout
#       - run:
#           name: Deploy to production
#           command: echo "Deploying to production"
# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master

version: 2.1

parameters:
  my_trigger_parameter:
    type: string
    default: ""

jobs:
  do-the-thing:
    docker:
      - image: node:14
    parameters:
      my_job_param:
        type: string
        default: "triggered by commit"
    steps:
      - run: echo << parameters.my_job_param >>

  do-the-thing2:
    docker:
      - image: node:14
    parameters:
      my_job_param:
        type: string
        default: "triggered by API/manually"
    steps:
      - run: echo << parameters.my_job_param >> 

workflows:
  # Workflow triggered by API call / hitting "Trigger Pipeline" in the web interface
  api-triggered-workflow:
    when: << pipeline.parameters.my_trigger_parameter >>
    jobs:
    - do-the-thing2:
        my_job_param: << pipeline.parameters.my_trigger_parameter >>
  # Workflow triggered only by pushing a commit to the repository
  commit-triggered-workflow:
    when:
      not: << pipeline.parameters.my_trigger_parameter >>
    jobs:
    - do-the-thing