version: 2.1

parameters:
  my_trigger_parameter:
    type: string
    default: ""

jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            npm install
            npm test
            node index
  deploy:
    docker:
      - image: node:14
    parameters:
      my_job_param:
        type: string
        default: "triggered by commit"
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: echo "Deploying to production"
workflows:
  version: 2.0
   # Workflow triggered by API call / hitting "Trigger Pipeline" in the web interface
  commit-triggered-workflow-build-and-deploy:
    when: 
      not: << pipeline.parameters.my_trigger_parameter >>
    jobs:
      - build
  api/manual-triggered-workflow-deploy:
    when: << pipeline.parameters.my_trigger_parameter >>
    jobs:
      - deploy:
          requires:
            - build
          my_job_param: << pipeline.parameters.my_trigger_parameter >>
          # filters:
          #   branches:
          #     only: master
